name: rich_readmore
description: A widget that displays text with an option to show more or show less based on the provided settings.
version: 1.1.1
repository: https://github.com/thierryoliveira/rich_readmore

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

